# Generated by Django 3.0.7 on 2020-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200930_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('FOOD', 'FOOD'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
