# Generated by Django 3.0.7 on 2020-10-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_auto_20200930_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('OTHERS', 'OTHERS')], max_length=255),
        ),
    ]
